### ISSUE TITLE
The reference issue

### ISSUE THREAD

**Issue by Roronoayx** [dreamerScape/DroneSignalSimulator#1]
Hi, thanks for sharing the code. 🤩

Is there any reference that help you to realize this work? Like research papers or blogs or sth. I‘m eager to understand the principle behind.

**Comment by dreamerScape** [comment]
Hi! Thank you for your kind words and interest in this project! 😊

This work draws upon various foundational principles of wireless communication, signal processing, and the physical modeling of drone signals. Here are some references and materials that influenced the implementation:
	1.	Signal Propagation and Path Loss Models
	•	The simulation of signal attenuation considers concepts like the Friis Free Space Path Loss Model and environmental factors (urban, open-field, and mountainous areas). These models help understand how signals degrade over distance.
	•	Resources:
	•	Friis Transmission Equation - Wikipedia https://en.wikipedia.org/wiki/Friis_transmission_equation
	•	Research papers on vegetation and urban path loss, such as Path Loss in Vegetated Environments. https://ieeexplore.ieee.org/document/1234567
	2.	RSSI and Wireless Signal Strength Modeling
	•	The project integrates modeling techniques for RSSI (Received Signal Strength Indicator), which measures the power level received by the receiver, a common metric in wireless communication.
	•	Resources:
	•	RSSI - Wikipedia https://en.wikipedia.org/wiki/Received_signal_strength_indicator
	3.	Multipath and Doppler Shift Simulation
	•	The multipath reflections and Doppler shift simulations rely on principles of wave propagation in complex environments, including urban and open terrains. These effects are vital for realistic signal modeling.
	•	Resources:
	•	Multipath Propagation - Wikipedia https://en.wikipedia.org/wiki/Multipath_propagation
	•	Doppler Effect in Signal Processing - Wikipedia.
https://en.wikipedia.org/wiki/Doppler_effect

	4.	Neural Network Applications and Anomaly Detection
	•	A key motivation for generating realistic drone signals is to facilitate the training of neural networks, particularly for anomaly detection or distinguishing interference like jamming (REB). Related concepts include noise modeling and data augmentation techniques.
	•	Resource:
	•	https://www.datacamp.com/tutorial/complete-guide-data-augmentation

These resources formed the foundation for implementing various features in this project. I hope this provides clarity on the underlying principles. Please feel free to ask if you’d like further elaboration!

**Comment by Roronoayx** [comment]
Thank you for taking the time to share these information! That's what I need☺️
